[package]
name = "snapdown"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
csv = "1.4.0"
ureq = { version = "3.1.4", features = ["rustls"] }
rayon = "1.10.0"
eframe = "0.33.3"
rfd = "0.17.2"
circular-buffer = "1.2.0"

